### ISSUE TITLE
execute more than one command at a time

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-parts#210]
Hey,

I'd like to know if there is a way to execute more than one command at once for e.g. via `LXDInstance.execute_run`.

I need to execute a number of commands. As `command` is a list of command parts, is this even possible? Would I need to pass in `;` or `&&` or would I need to create a command string which already combines the commands?

Or is there another way?

Thank you.

P.S.: I only care if all commands succeeded - I do not care which specifically failed.

**Comment by sergiusens** [comment]
Thanks for the issue, but is this a craft-providers issue or a craft-parts one?

**Comment by jugmac00** [comment]
You are absolutely right - this should go into `craft-providers`. Could you please move this issue and #211 - thank you!

**Comment by jugmac00** [comment]
I'll close this one and create a new one.
