### ISSUE TITLE
Request to have the Maven Plugin ported to craft-parts

### ISSUE THREAD

**Issue by frossm** [canonical/craft-parts#236]
I would respectfully ask that the Maven plugin be ported to craft-parts so it can be used moving forward.  Currently it does not work with core20 and I would imagine core22 when it is released.  Today we are all forced to use core18 and I'm sure in the future that will become unsupported.

This is a request based on the forum discussion with [cmatsuoka](https://forum.snapcraft.io/u/cmatsuoka).  

[LINK TO FORUM POST](https://forum.snapcraft.io/t/maven-plugin-missing-in-core20/29044/2)

I have quite a few Maven applications in the store and would happy to help test if that would be helpful.

Thank you so much.

Michael

**Comment by RetGal** [comment]
Just as reminder: Ubuntu 18.04 LTS support window closes on April 30, 2023.

**Comment by frossm** [comment]
Hello all.  With support stopping for 18.04LTS in a few months, is there plans to support maven in core22 and onwards?  I'm really enjoying using snaps, but without maven support, I'll probably need to stop in April.

I'd appreciate it if the devs could let us Java developers know their plans moving forward.  

Thank you.

Michael

**Comment by cmatsuoka** [comment]
A new maven plugin was added to Craft Parts 1.18.0 and is available in Snapcraft for `base: core22` snaps.
