### ISSUE TITLE
Incorrect origin use for priming, it should be the stage directory not the install dir

### ISSUE THREAD

**Issue by sergiusens** [canonical/craft-parts#414]
Contrast:
 
https://github.com/canonical/craft-parts/blob/main/craft_parts/executor/step_handler.py#L193

with

https://github.com/snapcore/snapcraft/blob/main/snapcraft_legacy/internal/pluginhandler/__init__.py#L930

The implications of the former is that any alteration done in stage is not reflected when priming.

**Comment by cmatsuoka** [comment]
The actual migration is performed with using the stage dir as the source (see https://github.com/canonical/craft-parts/blob/main/craft_parts/executor/step_handler.py#L198). The part install dir is used to get the list of files that can be migrated, similar to https://github.com/snapcore/snapcraft/blob/main/snapcraft_legacy/internal/pluginhandler/__init__.py#L840
