### ISSUE TITLE
Add new envvars for build-on and build-for architectures

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-parts#514]
### What needs to get done

| New environment variable  | Deprecated name|
| ------------- | ------------- |
| `CRAFT_ARCH_BUILD_ON`  | n/a |
| `CRAFT_ARCH_BUILD_FOR` | `CRAFT_TARGET_ARCH` |
| `CRAFT_ARCH_TRIPLET_BUILD_ON` | n/a |
| `CRAFT_ARCH_TRIPLET_BUILD_FOR` | `CRAFT_ARCH_TRIPLET` |

The deprecated environment variables will continue to work, but craft-parts should log a warning when a deprecated name is used.

### Why it needs to get done

- To give users access to architectures data when defining override scripts and environments.
- To align with the `build-on`/`build-for` naming convention

**Comment by cmatsuoka** [comment]
It's hard to tell when the old variable names are used when they're still defined. A warning for snapcraftctl use was added to snapcraft 7, but that's a shell command and the warning was added to a wrapper script.
