### ISSUE TITLE
Unregister bultin plugins

### ISSUE THREAD

**Issue by artivis** [canonical/craft-parts#619]
### What needs to get done

Add an option/function to unregister builtin plugins.

At the moment the [`unregister_all`](https://github.com/canonical/craft-parts/blob/0f5ec0ee704ef462e007437bce6c4749b318fab6/craft_parts/plugins/plugins.py#L119) function only unregister user-registered plugins.

### Why it needs to get done

We're working on a craft-application-based project that has no use for most of the builtin plugins.

**Comment by lengau** [comment]
This is done in https://github.com/canonical/craft-parts/pull/726 and will be released by @mr-cal shortly.

See: https://github.com/canonical/craft-parts/pull/726#discussion_r1601505842 for details.
