### ISSUE TITLE
`uv` python plugin

### ISSUE THREAD

**Issue by lengau** [canonical/craft-parts#706]
### What needs to get done

Either a separate plugin or an opt-in configuration option for the Python plugin to use [uv](https://github.com/astral-sh/uv) instead of standard `venv` and `pip`.

### Why it needs to get done

We should provide first-class support for multiple Python build systems

**Comment by tigarmo** [comment]
We currently have two draft PRs for this:
-  feat: uv python plugin #695 
- [experimental] UV support for Python plugins #825 

@lengau any thoughts on which approach we should follow?

**Comment by lengau** [comment]
@tigarmo I think we need both, though in different ways.

1. The `uv` plugin should set `UV_PROJECT_ENVIRONMENT={self.get_venv_directory()}` and `UV_FROZEN=1` and then use `uv sync` to set up the venv (or something similar)
2. We should have an option in the plain `python` plugin to use `uv venv` and `uv pip` rather than the system's `venv` and `pip`. This could also be something like offering a configuration to set the `venv` and `pip` commands.

**Comment by lengau** [comment]
Per conversation:

- Set `UV_PYTHON` to `$PARTS_PYTHON_INTERPRETER` so we're using the system Python (during the build steps, only if not already set)
- Set `UV_PYTHON_PREFERENCE=only-system` in the build environment.
