### ISSUE TITLE
Support setting JAVA_HOME in java plugin

### ISSUE THREAD

**Issue by vpa1977** [canonical/craft-parts#892]
### What needs to get done

Set JAVA_HOME environment variable in Java plugin to JDK found in the build environment.

- The plugin should examine build environment for  java installation and validate that it is a valid JDK by checking  ability of javac to compile a basic java file. 
- If multiple runtimes found, the plugin should use the highest one by default , unless overriden by user by setting JAVA_HOME environment variable in the plugin properties.

### Why it needs to get done

- JRE (Java runtime environment) cannot not be used to compile Java projects and it is found in the stage environment. 
- Build should use consistent JDK version between subsequent builds

**Comment by lengau** [comment]
I think this should be the first one worked on :-)
